version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
  - dependency-name: ember-data
    versions:
    - 3.24.0
    - 3.25.0
  - dependency-name: ember-cli-mirage
    versions:
    - 2.0.1
  - dependency-name: nypr-audio-services
    versions:
    - 0.6.0
  - dependency-name: start-server-and-test
    versions:
    - 1.12.0
  - dependency-name: ember-sortable
    versions:
    - 2.2.2
  - dependency-name: ember-sinon-qunit
    versions:
    - 5.0.0
  - dependency-name: ember-holygrail-layout
    versions:
    - 0.3.1
  - dependency-name: ember-moment
    versions:
    - 8.0.1
  - dependency-name: ember-body-class
    versions:
    - 2.0.0
  - dependency-name: ember-fetch
    versions:
    - 8.0.4
  - dependency-name: glob
    versions:
    - 7.1.6
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: bl
    versions:
    - 1.2.3
  - dependency-name: ember-cli-deploy-manifest
    versions:
    - 2.0.0
  - dependency-name: node-fetch
    versions:
    - 2.6.1
  - dependency-name: node-sass
    versions:
    - 4.14.1
  - dependency-name: jquery
    versions:
    - 3.5.1
  - dependency-name: https-proxy-agent
    versions:
    - 2.2.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: abortcontroller-polyfill
    versions:
    - 1.7.1
  - dependency-name: nypr-publisher-lib
    versions:
    - 0.5.10
